# Generated by Django 4.2.1 on 2023-05-18 07:39

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='videos'),
        ),
    ]
